In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
s1=pd.Series([7.3,-2.5,3.4,1.5], index=['a','c','d','e'])

In [3]:
s2=pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])

In [4]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [5]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [6]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [7]:
df1=pd.DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'), index=['Ohio','Texas','colorado'])

In [8]:
df2=pd.DataFrame(np.arange(12.).reshape((4,3)),columns=list('bce'), index=['Utah','Ohio','Texas','Oregon'])

In [9]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
colorado  6.0  7.0  8.0

In [10]:
df2

b     c     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [11]:
df1+df2

b     c   d   e
Ohio      3.0   5.0 NaN NaN
Oregon    NaN   NaN NaN NaN
Texas     9.0  11.0 NaN NaN
Utah      NaN   NaN NaN NaN
colorado  NaN   NaN NaN NaN

In [12]:
df1=pd.DataFrame({'A':[1,2]})

In [13]:
df2=pd.DataFrame({'B':[3,4]})

In [14]:
df1

A
0  1
1  2

In [15]:
df2

B
0  3
1  4

In [16]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [17]:
df1.add(df2,fill_value=0)

A    B
0  1.0  3.0
1  2.0  4.0

In [18]:
1/df1

A
0  1.0
1  0.5

In [19]:
df1.rdiv(1)

A
0  1.0
1  0.5

In [20]:
arr=np.arange(12).reshape((3,4))

In [21]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
arr[0]

array([0, 1, 2, 3])

In [23]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [24]:
frame=pd.DataFrame(np.arange(12.).reshape((4,3)),
                  columns=list('bde'),
                  index=['Utah','Ohio','Texas','Oregon'])

In [25]:
series=frame.iloc[0]

In [26]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [27]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [28]:
frame-series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [29]:
series2=pd.Series(range(3),index=['b','e','f'])

In [30]:
frame+series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [31]:
series3=frame['d']

In [32]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [33]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [34]:
frame.sub(series3,axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [35]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64